/* 
*   File: KJ_Tool_LeadController.cls
*   Authors: Slate Thompson (Slate@kintyjones.com)
*   Created: 6/10/2026
*   Description: This class is built to control operations related to the lead object

*/
public with sharing class KJ_Dispatch_LeadController extends KJ_Dispatch_AbstractController {

    //*-- Member Methods --------------------------------------------------------------------------
    public KJ_Dispatch_LeadController() {
        
    }
    protected String controllerName(){
        return 'KJ_Dispatch_LeadDispatch';
    }
    protected void route(KJ_Tool_Package pkg){
        
    }
}