/* 
*   File: KJ_Engine_HVACUnitEngine.cls
*   Authors: Slate Thompson (Slate@kintyjones.com)
*   Created: 7/24/2026
*   Description: This class is built to hold the operations needed for the HVAC Unit object
*/

public with sharing class KJ_Engine_HVACUnitEngine {
    public static void onBeforeInsert(){}
    public static void onBeforeUpdate(){}
    public static void onBeforeDelete(){}

    public static void onAfterInsert(){}
    public static void onAfterUpdate(){}
    public static void onAfterDelete(){}
    public static void onAfterUndelete(){}
}